[package]
name = "http_tls_client"
version = "0.1.0"
authors = ["real <real@freedomlayer.org>"]

[dependencies]
bytes = "0.4"
futures = "0.1"
tokio-io = "0.1"
tokio-tls = "0.1"
tokio-core = "0.1"
tokio-proto = "0.1"
tokio-service = "0.1"
native-tls = "0.1"
